---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g bower
  - npm install phantomjs-prebuilt

install:
  - npm install
  - bower install

script:
  - npm test

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `dist` directory containing the website.
    npm build
    cd dist
    git init
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://joukevandermaas:$GITHUB_API_KEY@github.com/profanus/profanus.github.io master &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
